import Head from 'next/head'
import Image from './components/Image';
import Link from 'next/link'
import { Inter } from '@next/font/google'

const inter = Inter({ subsets: ['latin'] })

export default function About() {
  return (
    <>
      <Head>
        <title>SSR Magician - About</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div style={{fontSize: '20px', color: 'blue' }}>
        <h1>About</h1>
        <div>
          <Image />       
        </div>
        <Link href='/'>
        <button>Home</button>
        </Link>
        <p>I was a magician once!</p>
      </div>
    </>
  )
}
