import Head from 'next/head'
import Link from 'next/link'
import App from './src/App';
import styles from './src/App.module.css'
import 'tachyons';


export default function Robofriends() {
  return (
    <>
        <Head>
          <title>SSR Magician - Robofriends App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
          <style>
          {`
            html,
            body {
              background: linear-gradient(to right, rgb(77, 136, 255), rgb(0, 26, 77));
              margin: 0;
              padding: 0;
            }
          `}
          </style>
        </Head>
        <div className={styles.container}>
          <App />
        </div>
        <div className='tc pa2'>
          <Link href ='/'>
            <button>Home</button>
          </Link>
        </div>
    </>
  )
}
